#!/bin/bash

# Einbinden der SetupHelper CommonResources
source "/data/SetupHelper/CommonResources"

# Pfaddefinitionen
configFile="/etc/venus/dbus-adc.conf"
sourceFileDir="/data/ExpanderPiSetup/FileSets"
overlays=("i2c-rtc.dtbo" "ds1307-rtc.dtbo" "mcp3208.dtbo")
overlayDir="/u-boot/overlays"
configTxt="/u-boot/config.txt"
rcLocalFile="/data/rc.local"
rcLocalContent=("echo ds1307 0x68 > /sys/class/i2c-adapter/i2c-1/new_device" "hwclock -s")

# Initialisierung von Variablen zur Neustartkontrolle
restartSystemRequired=false
restartGui=false

# Überprüfung der Kompatibilität
checkCompatibility

# Backup der Originaldateien
backupOriginals() {
    backupActiveFile "$configFile"
    backupActiveFile "$configTxt"
    backupActiveFile "$rcLocalFile"
}

# Installationsroutine
installConfigAndOverlays() {
    logMessage "Installiere und konfiguriere dbus-adc.conf und Overlays..."
    updateActiveFile "$sourceFileDir/dbus-adc.conf" "$configFile"
    updateConfigEntry "dtoverlay=i2c-rtc,ds1307-rtc" "$configTxt"
    updateConfigEntry "dtoverlay=mcp3208:spi0-0-present" "$configTxt"

    for overlay in "${overlays[@]}"; do
        updateActiveFile "$sourceFileDir/$overlay" "$overlayDir/$overlay"
    done

    executeAndAddToRcLocal "${rcLocalContent[@]}"
    restartSystemRequired=true
}

# Kernel-Module prüfen und installieren
checkAndInstallKernelModules() {
    for module in "${requiredModules[@]}"; do
        installKernelModule "$module"
    done
}

# Einträge zu rc.local hinzufügen und ausführen
executeAndAddToRcLocal() {
    for entry in "$@"; do
        if ! grep -qF -- "$entry" "$rcLocalFile"; then
            echo "$entry" >> "$rcLocalFile"
            eval "$entry"
        fi
    done
}

# Deinstallationsroutine
uninstall() {
    sed -i '/dtoverlay=i2c-rtc,ds1307-rtc/d' "$configTxt"
    sed -i '/dtoverlay=mcp3208:spi0-0-present/d' "$configTxt"
    removeRcLocalEntries "${rcLocalContent[@]}"

    for overlay in "${overlays[@]}"; do
        if [ -f "$overlayDir/$overlay" ]; then
            rm -f "$overlayDir/$overlay"
        fi
    done

    restoreActiveFile "$configFile"
    restartSystemRequired=true
}

# Entfernen spezifischer Einträge aus rc.local
removeRcLocalEntries() {
    for content in "$@"; do
        sed -i "/$content/d" "$rcLocalFile"
    done
}

# Hauptlogik
if [ "$scriptAction" == 'INSTALL' ]; then
    backupOriginals
    installConfigAndOverlays
    checkAndInstallKernelModules
elif [ "$scriptAction" == 'UNINSTALL' ]; then
    uninstall
fi

# System- oder GUI-Neustart, falls erforderlich
if $restartSystemRequired; then
    restartSystem
elif $restartGui; then
    restartGuiService
fi

# Abschluss der Skriptausführung
logMessage "Skriptausführung abgeschlossen."
endScript
